### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by francescoagati** [jcoglan/heist#1]
how about performance with ruby? It convert code in ruby and after exec? A program write in heist have the same performance of a program writ i nruby?

**Comment by jcoglan** [comment]
If you're concerned about performance, use a mature Scheme like Racket, or have a look at Clojure. Heist is just a toy interpreter (and the first one I wrote!), and is significantly slower than Ruby since it interprets the parse tree directly rather than compiling it. Calling something simple like `(+ 3 4)`, even if you write it in Ruby as `[:+, 3, 4]`, involves a lot of Ruby method calls inside the Heist runtime -- it doesn't just eval `3 + 4`.

**Comment by francescoagati** [comment]
ok but make a lisp that compile in ruby like do for example clojure that compile in java is possible with heist? There is an equivalente lisp that can be compiled in ruby without lost in performance and having the possibility of make macro and metaprogramming at compile type?

**Comment by francescoagati** [comment]
think a system for converting sexp lisp in sexp ruby

**Comment by jcoglan** [comment]
I'm not aware of a language like that does that, but you could use Heist to implement it. e.g. use `Heist.parse()` to parse the source code into sexp data (see the `Heist::Cons` class), then write a compiler to turn that into equivalent Ruby. Would be a good challenge, certainly more than I'm capable of!

**Comment by francescoagati** [comment]
ok thanks for the right direction. A questio sorry. In Heist you support also macro?

**Comment by jcoglan** [comment]
Yes, it supports the Scheme `syntax-rules` macro system -- see the `Heist::Runtime::Macro` class if you're curious. I also wrote [a blog post](http://blog.jcoglan.com/2010/01/20/adding-a-dynamic-defmacro-to-heist/) a while ago about adding a CL-style `defmacro` to Heist.

**Comment by francescoagati** [comment]
for be your first interpetrer is really good thanks
